### ISSUE TITLE
Renaming

### ISSUE THREAD

**Issue by nkt** [avevlad/gulp-ect#2]
Hi!
You are rename files, but that is not according to gulp's philosophy. May be you should remove

``` js
var fileName = gutil.replaceExtension(path.basename(file.path), "");
```

**Comment by avevlad** [comment]
![alt text](http://cdn.joxi.ru/uploads/prod/2014/01/26/eb8/c62/9e12d53497ad2b73f489d9b0849f7228c44aee38.png)

**Comment by nkt** [comment]
@AveVlad okay, i just fork it and make it better!
