### ISSUE TITLE
Error while trying to render template

### ISSUE THREAD

**Issue by maca** [avevlad/gulp-ect#8]
[gulp] Error gulp-ect: First argument needs to be a number, array or string.

**Comment by halcarleton** [comment]
+1

**Comment by jensljungblad** [comment]
+1

**Comment by n0bisuke** [comment]
+1

**Comment by The-Night-Watch** [comment]
+1

**Comment by avevlad** [comment]
+1

**Comment by jensljungblad** [comment]
Was this fixed?

**Comment by leehambley** [comment]
No, I'm here to give a +1, I assume it's because `gulp-ect` is more than a year since the last update, I'm leaning towards this being a problem with incompatibility with gulp API changes or something.
